/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sun.gltf --transform 
Files: sun.gltf [6.33KB] > E:\fullstack\frontend\React\StoneX\stonex\public\3d_models\sun\sun-transformed.glb [997.04KB] (-15651%)
Author: imperioame (https://sketchfab.com/imperioame)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sun-star-with-procedural-textures-7fc327e768574566b90fbb7b7602d289
Title: Sun / Star with procedural textures
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/3d_models/sun/sun-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Planeta009_09Sun_0.geometry}
        material={materials["09.Sun"]}
        rotation={[-2.083, 0.146, 0.212]}
        scale={0.002}
      />
    </group>
  );
}

useGLTF.preload("/3d_models/sun/sun-transformed.glb");
